services:
  asset-management-web:
    build:
      context: .
      dockerfile: Dockerfile
    image: asset-management-web
    container_name: asset-management-web
    ports:
      - "4300:80"  # Changed from 4300:4300
    restart: unless-stopped