import { Routes } from '@angular/router';
import { DashboardComponent } from './dashboard/dashboard';
import { AssetsComponent } from './components/assets/assets';
import { AddAssetComponent } from './components/add-asset/add-asset';
import { ServiceRequestsComponent } from './components/service-requests/service-requests';
import { CreateServiceRequestComponent } from './components/service-requests/create-service-request';
import { WorkOrderManagementComponent } from './components/work-order/work-order';
import { CreateWorkOrderComponent } from './components/work-order/create-work-order';
import { PreventiveMaintenanceComponent } from './components/preventive-maintenance/preventive-maintenance';
import { CreatePreventiveMaintenanceComponent } from './components/preventive-maintenance/create-preventive-maintenance';
import { ViewPreventiveMaintenanceComponent } from './components/preventive-maintenance/view-preventive-maintenance';
import { InventoryComponent } from './components/inventory/inventory';
import { CreateInventoryComponent } from './components/inventory/create-inventory';
import { VendorManagementComponent } from './components/vendor-management/vendor-management';
import { CreateVendorComponent } from './components/vendor-management/create-vendor';
import { ViewVendorComponent } from './components/vendor-management/view-vendor';
import { ViewInventoryComponent } from './components/inventory/view-inventory';
import { ProcurementComponent } from './components/procurement/procurement';
import { CreateProcurementComponent } from './components/procurement/create-procurement';
import { ServiceContractComponent } from './components/service-contract/service-contract';
import { CreateServiceContractComponent } from './components/service-contract/create-service-contract';
import { FailureCodeComponent } from './components/failure-code/failure-code';
import { CreateFailureCodeComponent } from './components/failure-code/create-failure-code';
import { ViewAssetComponent } from './components/view-asset/view-asset';
import { ViewServiceRequestComponent } from './components/view-service-request/view-service-request';
import { ViewWorkOrderComponent } from './components/view-work-order/view-work-order';
import { TechnicianComponent } from './components/technician/technician';
import { CreateTechnicianComponent } from './components/technician/create-technician';
import { ViewTechnicianComponent } from './components/technician/view-technician';
import { TechnicianTeamsComponent } from './components/technician/technician-teams';
import { CreateTechnicianTeamComponent } from './components/technician/create-technician-team';
import { ViewTechnicianTeamComponent } from './components/technician/view-technician-team';
import { LoginComponent } from './components/login/login';
import { RolesComponent } from './components/roles/roles';

export const routes: Routes = [
  { path: '', pathMatch: 'full', redirectTo: 'login' },
  { path: 'login', component: LoginComponent },
  { path: 'dashboard', component: DashboardComponent },
  { path: 'assets/add-asset', component: AddAssetComponent },
  { path: 'assets/add-asset/:tab', component: AddAssetComponent },
  { path: 'assets', component: AssetsComponent },
  { path: 'assets/view/:id', component: ViewAssetComponent },
  { path: 'service-requests/create', component: CreateServiceRequestComponent },
  { path: 'service-requests/edit/:id', component: CreateServiceRequestComponent },
  { path: 'service-requests/view/:id', component: ViewServiceRequestComponent },
  { path: 'service-requests', component: ServiceRequestsComponent },
  { path: 'work-orders/create', component: CreateWorkOrderComponent },
  { path: 'work-orders/edit/:id', component: CreateWorkOrderComponent },
  { path: 'work-orders/view/:id', component: ViewWorkOrderComponent },
  { path: 'work-orders', component: WorkOrderManagementComponent },
  { path: 'technicians', component: TechnicianComponent },
  { path: 'technicians/create', component: CreateTechnicianComponent },
  { path: 'technicians/edit/:id', component: CreateTechnicianComponent },
  { path: 'technicians/view/:id', component: ViewTechnicianComponent },
  { path: 'technicians/teams/create', component: CreateTechnicianTeamComponent },
  { path: 'technicians/teams/edit/:id', component: CreateTechnicianTeamComponent },
  { path: 'technicians/teams/view/:id', component: ViewTechnicianTeamComponent },
  { path: 'technicians/teams', component: TechnicianTeamsComponent },
  { path: 'preventive-maintenance', component: PreventiveMaintenanceComponent },
  { path: 'preventive-maintenance/create', component: CreatePreventiveMaintenanceComponent },
  { path: 'preventive-maintenance/edit/:id', component: CreatePreventiveMaintenanceComponent },
  { path: 'preventive-maintenance/view/:id', component: ViewPreventiveMaintenanceComponent },
  { path: 'inventory', component: InventoryComponent },
  { path: 'inventory/create', component: CreateInventoryComponent },
  { path: 'inventory/edit/:id', component: CreateInventoryComponent },
  { path: 'inventory/view/:id', component: ViewInventoryComponent },
  { path: 'vendor-management', component: VendorManagementComponent },
  { path: 'vendor-management/create', component: CreateVendorComponent },
  { path: 'vendor-management/edit/:id', component: CreateVendorComponent },
  { path: 'vendor-management/view/:id', component: ViewVendorComponent },
  { path: 'procurement', component: ProcurementComponent },
  { path: 'procurement/material-requisitions', component: ProcurementComponent },
  { path: 'procurement/purchase-orders', component: ProcurementComponent },
  { path: 'procurement/goods-receipts', component: ProcurementComponent },
  { path: 'procurement/create', component: CreateProcurementComponent },
  { path: 'service-contracts', component: ServiceContractComponent },
  { path: 'service-contracts/create', component: CreateServiceContractComponent },
  { path: 'failure-codes', component: FailureCodeComponent },
  { path: 'failure-codes/create', component: CreateFailureCodeComponent },
  { path: 'roles-permissions', component: RolesComponent }
];
